dist: trusty
language: node_js
node_js:
  - "12"
sudo: required

env:
  # Path to 'hadolint' binary
  HADOLINT: "${HOME}/hadolint"

services:
  - docker
before_script:
  - npm install
  - curl -sL -o ${HADOLINT} "https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-$(uname -s)-$(uname -m)"
      && chmod 700 ${HADOLINT}
script:
  - hadolint.sh
   - docker build -t covid19-tracker .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag covid19-tracker $DOCKER_USER/covid19-tracker:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/covid19-tracker:$TRAVIS_BUILD_NUMBER
  - docker tag covid19-tracker $DOCKER_USER/covid19-tracker:latest
  - docker push $DOCKER_USER/covid19-tracker:latest

