dist: trusty
language: node_js
node_js:
  - "12"
sudo: required


jobs:
  include:

- stage: Leaks
        language: generic
        script:
          - "./hadolint.sh"

- stage: Leaks
      language: generic
      script:
        - "./leaks.sh"
services:
  - docker
before_script:
  - npm install

script:
   - docker build -t covid19-tracker .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag covid19-tracker $DOCKER_USER/covid19-tracker:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/covid19-tracker:$TRAVIS_BUILD_NUMBER
  - docker tag covid19-tracker $DOCKER_USER/covid19-tracker:latest
  - docker push $DOCKER_USER/covid19-tracker:latest

