version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          context: AWS
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: /root
          profile-name: myProfileName
          region: AWS_REGION_ENV_VAR_NAME
          repo: docker/repo
          skip-when-tags-exist: false
          tag: 'latest'
