version: 2.1
orbs:
  ggshield: gitguardian/ggshield@volatile
  trivy: signavio/trivy@1.1.0
  aws-ecr: circleci/aws-ecr@6.15.3
  docker: circleci/docker@1.5.0
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:

  dockle:
    docker:
      - image: docker:19.03-git
    steps:
      - checkout
      - setup_remote_docker
         version: 19.03.13
      - run:
          command: |
            wget https://github.com/goodwithtech/dockle/releases/download/v0.2.0/dockle_0.2.0_Linux-64bit.tar.gz
            tar zxvf dockle_0.2.0_Linux-64bit.tar.gz
            mv dockle /usr/local/bin
      - run:
          command: |
            dockle --exit-code 0 python:3.4-alpine

  container-scan:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build image
          command: docker build -t trivy-ci-test:${CIRCLE_SHA1} .
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            VERSION=$(
                curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | \
                grep '"tag_name":' | \
                sed -E 's/.*"v([^"]+)".*/\1/'
            )
            wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
            tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
            mv trivy /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy --exit-code 1 --severity CRITICAL --no-progress trivy-ci-test:${CIRCLE_SHA1}

workflows:
  version: 2
  build-master:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io
      - dockle:
          filters:
            branches:
              only: master
      - ggshield/scan:
          name: ggshield-scan
          base_revision: << pipeline.git.base_revision >>
          revision: <<pipeline.git.revision>>
      - container-scan:
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          requires:
            - docker/hadolint
            - dockle
            - ggshield-scan
            - container-scan
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: 'latest'
          account-url: AWS_ECR_ACCOUNT_URL
          region: AWS_DEFAULT_REGION
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag='latest'"
