version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  update-tag:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_DEFAULT_REGION
      - aws-ecs/update-service:
          cluster-name: 'myCluster'
          container-image-name-updates: 'container=tracker,tag=stable'
          family: 'tracker'
workflows:
  deploy:
    jobs:
      - update-tag