version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  update-tag:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          cluster-name: 'myCluster'
          container-image-name-updates: 'docker/repo:00000, stable'
          family: 'Covid19Tracker'
workflows:
  deploy:
    jobs:
      - update-tag